### ISSUE TITLE
JDBC PreparedStatement not placing Parameters in {1} 

### ISSUE THREAD

**Issue by FossilBlade** [neo4j/neo4j-jdbc#150]
The following code isnt executing:

```
String query = "MATCH (n:?) RETURN n";	
try (PreparedStatement stmt = conn.prepareStatement(query)) {
	stmt.setString(1, "classes");
	ResultSet rs = stmt.executeQuery();
	while (rs.next()) {
		System.out.println("Friend: " + rs.getString("n.name"));
		return (Map) rs.getObject("n");
	}
}

```
Giving Error: Invalid input '{': expected whitespace or a label name (line 1, column 10 (offset: 9)) "MATCH (n:{1}) RETURN n"

**Comment by omarlarus** [comment]
Hi @raushan2003 , your issue is not about JDBC. You get the error because you cannot use dynamic parameters for Label. If you want to write a query like that, you need to replace (string concatenation) the Label into the cypher. 

If you need support about cypher, try [here](https://support.neo4j.com/hc/en-us)

**Comment by jexp** [comment]
Also:

1. you must use `{1}` etc, not `?`
2. Parameter Numbers in JDBC start with `1`

**Comment by conker84** [comment]
I'm closing this since this is not a real issue. Feel free to reopen it
