### ISSUE TITLE
don't fail with an error on unknown jdbc URLs, e.g. from other drivers

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#184]
see: 
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1061#issuecomment-459390972

**Comment by conker84** [comment]
The referenced bug has been fixed by #113 in branch (v `3.4`). The guy in the APOC issue used v. `3.1.0`
I made a test with the following compose file:
https://gist.github.com/conker84/78495f3e7b27842860363a9a2eaf7d89
I create a `test` db with a table `prova` with 2 records
<img width="1554" alt="Schermata 2019-04-11 alle 11 19 19" src="https://user-images.githubusercontent.com/1833335/55945786-c477d100-5c4b-11e9-8669-2f5b177f02f9.png">
I also created a node into Neo4j and retrieved it via jdbc:
<img width="1550" alt="Schermata 2019-04-11 alle 11 20 41" src="https://user-images.githubusercontent.com/1833335/55945929-fdb04100-5c4b-11e9-806b-bc81779e09c5.png">
Let me know if you want some other tests othewise we can close this issue
