### ISSUE TITLE
Fix Bolt autocommit support

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#377]
Currently, [JDBC Connection](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setAutoCommit(boolean))'s `autocommit` is emulated with Neo4j driver's explicit transactions.

This causes at least two problems further down the line:

1. explicit transactions do not support `USING PERIODIC COMMIT` or `CALL {} IN TRANSACTIONS`. JDBC users just cannot run these constructs at the moment.
2. since this JDBC connector only supports [`ResultSet#CLOSE_CURSORS_AT_COMMIT`](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#CLOSE_CURSORS_AT_COMMIT), we have no other way than loading the results in memory for autocommit if users want to interact with the result set (the original iterator will be consumed at commit time, since the explicit transaction is automatically committed)

To fix this, the JDBC Bolt connector needs to run `Session#run` and instead of opening an explicit transaction when the connection is set to use autocommit. I believe doing this for autocommit will also solve point 2, since autocommit results are available until the underlying cursor is fully consumed, and this is driven by the user calls to the result set.

**Comment by drraghavendra** [comment]
JDBC uses an operation mode called auto-commit. This means that every update to the database is immediately made permanent.

Any situation where a logical unit of work requires more than one update to the database cannot be done safely in auto-commit mode. If something happens to the application or the system after one update is made and before any other updates are made, the first change cannot be undone when running in auto-commit mode.

Because changes are instantly made permanent in auto-commit mode, there is no need for the application to call the commit method or the rollback method. This makes applications easier to write.

Auto-commit mode can be enabled and disabled dynamically during a connection's existence. Auto-commit is enabled in the following way, assuming that data source already exists:

So Please enable the feature asap.

**Comment by fbiville** [comment]
Hello @drraghavendra, pasting the definition of autocommit and concluding your comment with:
> So Please enable the feature asap.
is not really helpful. Please comment issues only if you have specific details you want to share.

**Comment by michael-simons** [comment]
Version 6 fully supports these kinda queries as long as the JDBC connection is in auto commit mode.
