### ISSUE TITLE
ResultSetMetaData.getColumnTypeName(int i) throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by PavloPolovyi** [neo4j/neo4j-jdbc#419]
When the ResultSet is empty, when accessing the ResultSetMetaData.getColumnTypeName(int i) throws NullPointerException ( Line 61 of BoltNeo4jResultSetMetaData). Sample query:
```code
PreparedStatement statement = connection.prepareStatement("MATCH(P:Person) WHERE P.date >= ? AND P.date  < ?) RETURN P");
statement.setTimeStamp(1, any value);
statement.setTimeStamp(2, any value);
ResultSet resultSet = statement.getResultSet();
ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
int columnCount = resultSetMetaData.getColumnCount(); // it equals 1 for sample query
for (int c = 1; c < columnCount + 1; c++) {
                String label = resultSetMetaData.getColumnLabel(c); // P
                int type = resultSetMetaData.getColumnType(c);//2000
                String typeName = resultSetMetaData.getColumnTypeName(c); <- NullPointerException
}              

```
Driver version: 4.0.9
Java: 8
Platform: Windows 11
Neo4j:4.0 but with newer one also, tested on 5.5.0

**Comment by conker84** [comment]
@PavloPolovyi  thank you so much for pointing this out.
After a discussion with @fbiville we agreed that this is not a real bug because, as the dataset is empty, and given the fact that Neo4j is schemaless, we're not able to retrieve the type of the column that we compute from the result. One change that we want to do is to throw a better exception like:
```
java.sql.SQLException: Column type cannot be determined (data set is empty)
```
