### ISSUE TITLE
Test with Matlab [and docs]

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#6]

**Comment by glaggia-larus** [comment]
To start a connection with neo4j you first need to let matlab know of the existence of the driver jar

<img width="1273" alt="screen shot 2018-01-02 at 17 32 44" src="https://user-images.githubusercontent.com/12963831/34491594-52a2f96c-efe4-11e7-935e-bd4e537d3069.png">

with javaclasspath you can check that there are no neo4j jars available in the class path.

<img width="1273" alt="screen shot 2018-01-02 at 17 32 51" src="https://user-images.githubusercontent.com/12963831/34491621-723a6d14-efe4-11e7-854f-0067fc0586d7.png">

add the jar to the path with javaaddpath

<img width="1273" alt="screen shot 2018-01-02 at 17 33 37" src="https://user-images.githubusercontent.com/12963831/34491650-87d857a8-efe4-11e7-819e-b10424dcb3fc.png">

and check that the dynamic path contains the jar

<img width="1273" alt="screen shot 2018-01-02 at 17 33 50" src="https://user-images.githubusercontent.com/12963831/34491669-98b00d96-efe4-11e7-8bf2-713c651fa27d.png">

create a connection specifying username, password, the driver class and the URL:
<img width="1560" alt="screen shot 2018-01-02 at 17 35 44" src="https://user-images.githubusercontent.com/12963831/34491691-b4d14f8a-efe4-11e7-897a-6f6a06baa4ed.png">

If the connection is successful you will get a message like this:
<img width="1560" alt="screen shot 2018-01-02 at 17 35 51" src="https://user-images.githubusercontent.com/12963831/34491711-d06858e2-efe4-11e7-96de-941f4ac06844.png">

The database has to be started. In my database I've used the basic movie database.
You can fetch some data from the connection using fetch:

<img width="1560" alt="screen shot 2018-01-02 at 17 36 51" src="https://user-images.githubusercontent.com/12963831/34491743-f8613134-efe4-11e7-9e30-0a67878ad76c.png">
<img width="1560" alt="screen shot 2018-01-02 at 17 36 57" src="https://user-images.githubusercontent.com/12963831/34491748-fe53dd1c-efe4-11e7-8bfd-3f06f77cc4d7.png">

to activate the table visualisation instead of the "cellarray" visualisation you have to set the correct property
```setdbprefs('DataReturnFormat', 'table')```

**Comment by jexp** [comment]
@glaggia-larus did you add this all to the docs?

I also did some experiments back then (totally forgot that we had this here as an issue):
http://gist.asciidoctor.org/?dropboxs-ovkhon37z64l5bh%2Fmatlab-neo4j.adoc%3Fdl%3D0

**Comment by glaggia-larus** [comment]
I will add this to the docs asap and I will take the document you linked to me as example and starting point.

I reopen this as reminder
