### ISSUE TITLE
Test with LibreOffice

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#7]

**Comment by sim51** [comment]
# Step 1: Adding jar to Libre Office
- Open Libre Office
- Go to `menu > Tools > Options`
- In the new window, select in the tree `LibreOffice > Advanced`
- Click on the button `Class Path` button 
- Click on `Add an archive` and select the JDBC driver
  ![image](https://cloud.githubusercontent.com/assets/231657/15985203/14fd151c-2fe6-11e6-842a-b953fb900caf.png)

# Step 2 : Create a Neo4j database
- Create a new database and choose the JDBC connection
  ![image](https://cloud.githubusercontent.com/assets/231657/15985212/49aeacc6-2fe6-11e6-93ec-18088c405531.png)
- Fulfill the datasource url and the driver class
  ![image](https://cloud.githubusercontent.com/assets/231657/15985215/68b7c3dc-2fe6-11e6-8ac2-cca411260866.png)
- Fulfill the username and test the connexion
  ![image](https://cloud.githubusercontent.com/assets/231657/15985221/8a061188-2fe6-11e6-8754-5c3f2b24c5c5.png)
- Save your new LibreOffice database

# Step 3: Make some queries
- Click on `Queries` tab, and after on `Create a query in SQL mode ...`
- The SQL editor should appears.  To allow you to make some Cypher queries, click on the button `SQL` (otherwise LibreOffice try to make a SQL validation of your query)
- Make a query and execute it !

![image](https://cloud.githubusercontent.com/assets/231657/15985264/e11c1fac-2fe7-11e6-9c4d-8f09ad9edfc0.png)
