### ISSUE TITLE
README: Proposal for "Run query" of "Minimum viable snippet"

### ISSUE THREAD

**Issue by tommystanton** [neo4j/neo4j-jdbc#75]
This snippet example shows use of the `user` and `password` query params (which are presently documented further in the README, after the snippet).  Also, it makes use of a `CALL` query that should work on any given Neo4j instance.

The snippet will print out something like:

``` text
Component Neo4j Kernel is present
```

---
### Minimum viable snippet

...
#### Run Query

``` java
// Connect
Connection con = DriverManager.getConnection("jdbc:neo4j:bolt://localhost/?user=neo4j&password=neo4j");

// Querying
String query = "CALL dbms.components()";
PreparedStatement stmt = con.prepareStatement(query);

ResultSet rs = stmt.executeQuery();

while (rs.next()) {
    System.out.println("Component " + rs.getString("name") + " is present");
}
```

**Comment by inserpio** [comment]
Hi @tommystanton, we can add `user` and `password` params, but I'm keen not to use a stored procedure in the min snippet because the http module (and in future the in-memory and file ones) is meant to work also with previous to 3.0 neo4j versions. Store procedure are available from 3.0, and I don't want users to think that this driver is only for neo4j 3.X: I personally prefer to leave a cypher query. I know it pretends for you to have the movie example loaded into the neo4j instance so the query won't return anything if you don't load it, but in the end the snippet is just meant to show the user how to use various classes/interfaces.

**Comment by sim51** [comment]
Like @inserpio, I'm ok for adding`user` & `password` into the snippet, and to keep the cypher query.

**Comment by tommystanton** [comment]
I'm not married to the example I proposed; I think I was having trouble getting the present example in the README to compile (it was the first time I saw use of the try-with-resources syntax).

**Comment by jexp** [comment]
Yes, no need to introduce procedure call syntax. 
We can add it in the docs to demonstrate how to use it with params.

But I'm for adding username + password. But via DriverManager.getConnection(url, username, password)

**Comment by inserpio** [comment]
username + password added as suggested by @jexp.
