### ISSUE TITLE
Test with Eclipse BIRT

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#8]

**Comment by ClaudioStevanato** [comment]
Here is a procedure on how to use Neo4J JDBC driver with Eclipse BIRT:

To install BIRT we can use "Install New Software" that is located on the Help menu in Eclipse
After opening Install New Software tool we can add a site with "Add" button at the top-right of the opened window
There we can give a name to our site and also a link to where download the platform BIRT, here's a reference to all the recent BIRT releases:
http://wiki.eclipse.org/BIRT_Update_Site_URL

Now we can start with our BIRT Project
1.Start a new Project by clicking "Report Project" under BIRT folder
![1](https://cloud.githubusercontent.com/assets/16083115/16528407/094a06da-3fbd-11e6-8c7c-2eb0750881e5.png)

2.Choose the project name, after clicking Next, Eclipse advice us that Report Design perspective will be opened (if it's not yet)
![2](https://cloud.githubusercontent.com/assets/16083115/16528424/2c7bc31e-3fbd-11e6-8a12-b2aef14aa4fc.png)

3.Create a new Report inside our project by clicking File -> New -> Report
(Missing image because of unable to take a screenshot while my Eclipse menu is opened)

4.Choose a file name for our project, then click Next
![4](https://cloud.githubusercontent.com/assets/16083115/16528443/4caf494e-3fbd-11e6-9915-c6569d36942f.png)

5.Select a Blank report, or, if wanted, another template
![5](https://cloud.githubusercontent.com/assets/16083115/16528514/a40d8e08-3fbd-11e6-837d-c76772261b3b.png)

6.Click finish, in our Data Explorer we will see folder where we can create our Data Sources and Data Set, right click on Data Source and click "New Data Source"
(Missing image because of unable to take a screenshot while my Eclipse menu is opened)

7.Choose "create from a connection profile in the profile store" checkbox, we are choosing a custom profile because we need to add Neo4j JDBC driver
![6](https://cloud.githubusercontent.com/assets/16083115/16528549/bd362cd2-3fbd-11e6-873c-70d812008508.png)

8.Here we can choose a precedentely created Profile Store or create a new one, click on New
![7](https://cloud.githubusercontent.com/assets/16083115/16528623/356edae6-3fbe-11e6-86b9-6111f4325f9b.png)

9.Let's click again the New button
![8](https://cloud.githubusercontent.com/assets/16083115/16528640/64808de8-3fbe-11e6-9f9e-63687acd7f5a.png)

10.Let's choose "BIRT JDBC Data Source" and give a name to our Profile
![9](https://cloud.githubusercontent.com/assets/16083115/16528665/8491a0e0-3fbe-11e6-861d-6dfc0a119ec5.png)

11.Here we can choose from a driver loaded recently. To load a new driver, let's click Manage Drivers button to add our Neo4j JDBC driver
![10](https://cloud.githubusercontent.com/assets/16083115/16528673/9930a122-3fbe-11e6-92b7-8d01b2e40738.png)

12.Here we can add a new driver by clicking the Add button, in this window we can see our drivers and manage their jar files
![11](https://cloud.githubusercontent.com/assets/16083115/16528704/c247d4fe-3fbe-11e6-89a9-dea51aeb8033.png)

13.Select our Neo4j JDBC driver jar
![12](https://cloud.githubusercontent.com/assets/16083115/16528730/e6896b20-3fbe-11e6-8e88-541083ff0410.png)

14.We can see here the properties of our jars and the drivers contained in them (by switching from Jar on the Drivers tab)
![13](https://cloud.githubusercontent.com/assets/16083115/16528741/f64c29f8-3fbe-11e6-833f-9bcbfb97f9d8.png)

15.In this image we see the configuration that our driver has, we can also test our connection to see if it's everything alright
![14](https://cloud.githubusercontent.com/assets/16083115/16528766/24fa9f32-3fbf-11e6-9bb5-56b8056d796f.png)

16.Click next and then Finish
![15](https://cloud.githubusercontent.com/assets/16083115/16528796/50ed2286-3fbf-11e6-86e6-0edf9170b303.png)

17.Let's select our created Profile and specify a file name (this file will cointain the JDBC connection configurations for a Data Source)
![16](https://cloud.githubusercontent.com/assets/16083115/16528803/5a618a50-3fbf-11e6-961d-2aaa4fafb98d.png)

18.Click next to finish the setup of our Data Source
![17](https://cloud.githubusercontent.com/assets/16083115/16528853/a9fbe998-3fbf-11e6-8be0-f0de504e58d8.png)

19. Click Finish to create our Data Source, we can also re-test our connection to our database instance
![18](https://cloud.githubusercontent.com/assets/16083115/16528866/bb1ee6d0-3fbf-11e6-8be3-80485b06f74d.png)

20.Let's create now a Data Set by clicking right mouse button over Data Set folder in our Data Explorer view
![19](https://cloud.githubusercontent.com/assets/16083115/16528888/dba58ad0-3fbf-11e6-9933-396ee8e03493.png)

21.Here the first thing to do is choose a profile and set a name for our set, for example Movies
![20](https://cloud.githubusercontent.com/assets/16083115/16528907/f46d3a68-3fbf-11e6-8a1d-e0e50af5de73.png)

Note: this demonstration use the database created with Neo4j dataset ":play movie", this is why we used Movies as the name of our Data Set

22.Let's write a Cypher query that will return 5 movies
![21](https://cloud.githubusercontent.com/assets/16083115/16528934/36fe70ea-3fc0-11e6-8a32-5613e7da5a98.png)

23.If the query is written correctly, we will go to the next window where we can see our Output Columns and our Preview Results (in JSON format)
![22](https://cloud.githubusercontent.com/assets/16083115/16528946/4c2ea066-3fc0-11e6-9ee7-4ca110c3beb8.png)
![23](https://cloud.githubusercontent.com/assets/16083115/16528974/6ee680c4-3fc0-11e6-8c51-4ed588a794d9.png)

24.Under our Data Sets we will see our data set "Movies" and our result "m", which by dragging it into the report designer we can add a reference to it
![24](https://cloud.githubusercontent.com/assets/16083115/16529000/95932ad8-3fc0-11e6-85df-4cb3c55fb265.png)

25.We can also choose other graphic elements from our palette
![25](https://cloud.githubusercontent.com/assets/16083115/16529055/f1885520-3fc0-11e6-91ac-0487a89d7097.png)

26.We can still reference our result to be in a row in the table, or we can also add other elements such as labels, dynamic text, images etc
![26](https://cloud.githubusercontent.com/assets/16083115/16529077/15afa6ba-3fc1-11e6-8a58-aa1cfa702efe.png)

**Comment by jexp** [comment]
Perhaps we can return the individual properties of a movie? like title, year, tagline? Might make it easier to create an report from than just the JSON data ?

**Comment by albertodeste** [comment]
1. Start a new "Report project" under "Report design" perspective
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531592/82aa4d36-3fcd-11e6-8865-17d044d34743.png)
2. Select the project's name
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531611/9ffe01d4-3fcd-11e6-8e45-c9f3841a8436.png)
3. Create a new report (File->New->Report) and give it a name
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531682/e9dce37e-3fcd-11e6-84c4-83c3e7547b46.png)
4. Choose your template
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531712/04240596-3fce-11e6-9e97-b8e611e48a44.png)
5. Create a new Datasource by right clicking "Data sources" -> New Data Source and choose the second option
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531815/79956734-3fce-11e6-8141-5777f15399e9.png)
6. Create a new Connection profile store (click new on both windows)
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531873/cf2ad59e-3fce-11e6-911c-999f8b6f2cd0.png)
7. Choose "BIRTH JDBC Data Source" and give it a name
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531895/f0ec6904-3fce-11e6-88c8-5be6e62ed8bd.png)
8. Load your jdbc jar by clicking "Manage Drivers" and select "Add"
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531929/2d32090a-3fcf-11e6-893d-ed4ccef968c4.png)
9. Choose your dirver location and press OK
   ![image](https://cloud.githubusercontent.com/assets/13695124/16531945/3fce59f6-3fcf-11e6-9fe7-f7ecca4716db.png)
10. Fill the driver connection parameters
    ![image](https://cloud.githubusercontent.com/assets/13695124/16531965/59d8e352-3fcf-11e6-8458-5faf8fea540f.png)
11. Click "Next" and "Finish" and choose the newly created connection profile store
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532005/85f3630e-3fcf-11e6-9521-902bc61e5d8b.png)
12. Click "Next" and "Finish" and the Data Source should be created
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532102/06b6a280-3fd0-11e6-88e7-0d6f8bc79928.png)
13. Create a new Dataset (right click Data Sets -> New Data Set) and choose Next
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532142/4521c4d2-3fd0-11e6-8fae-bb3e0aee3e4f.png)
14. Type the query you want to create your Dataset with and click Finish
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532158/698c4a36-3fd0-11e6-8ef1-2126cad983a1.png)
15. A new Window will appear showing the columns available with your query
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532173/83925a2e-3fd0-11e6-9e92-cd8276a24c41.png)
16. You can also preview the results 
    ![image](https://cloud.githubusercontent.com/assets/13695124/16532199/9ffde6ec-3fd0-11e6-9d32-ecb0ab797e7e.png)
17. Close this window and create a new Table element (Right click the document -> Insert -> Table)
    ![schermata del 2016-07-01 21 32 58](https://cloud.githubusercontent.com/assets/13695124/16532646/848ca81e-3fd3-11e6-9f85-aeed3f4e0092.png)
18. Choose 4 columns and click Finish
    ![schermata del 2016-07-01 22 22 04](https://cloud.githubusercontent.com/assets/13695124/16533601/44c07b28-3fda-11e6-8273-a4b4c0d55545.png)
19. Fill the table with the following data (drag and drop the datasource colums in the right position)
    ![schermata del 2016-07-01 22 26 44](https://cloud.githubusercontent.com/assets/13695124/16533694/edf3b98a-3fda-11e6-9d80-f4026e036770.png)
20. To export the report click Run -> View report -> As PDF
    ![schermata del 2016-07-01 22 27 54](https://cloud.githubusercontent.com/assets/13695124/16533721/181e062a-3fdb-11e6-89eb-3a14c959e53b.png)
